### ISSUE TITLE
Is there a way to set global joi config?

### ISSUE THREAD

**Issue by yuxizhe** [koajs/joi-router#85] opened 2019-04-01 07:52 UTC
I want to set joi `allowUnknown` as a global config, because I don't mind what additional fields are passed in as long as the fields I want are supplied.
I have to set `allowUnknown` in every Joi valid code, is there a way to set global Joi config like this below?

```js
const router = require('koa-joi-router');
const pub = router({
  validate: {
    allowUnknown: true,
  },
});
```

**Comment by Saghen** [comment] 2019-04-03 08:22
I have implemented this functionality in my fork: https://github.com/Saghen/joi-router

It has support for a custom error handler and default spec. In your case, simply do:
```js
const pub = router({
  spec: {
    validate: {
      allowUnknown: true,
    }
  }
});
```
and here is how to use a custom error handler
```js
const blog = router({
  errorHandler: function(ctx, type, err) {
    // In my case I have a request builder in my ctx via app.context.buildError = myFunction
    ctx.buildError({ 
      status: err.status,
      errors: [{
        message: err.message
      }]
     })
  }
});
```

**Comment by yuxizhe** [comment] 2019-04-03 11:38
@Saghen Thanks for your replay!  Its very helpful 👍 .

**Comment by aheckmann** [comment] 2019-04-27 22:07
Closing as duplicate of #41.

**Closed by aheckmann** 2019-04-27 22:07 UTC
